name: Create Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create frozen requirements
      run: |
        pip freeze > requirements-frozen.txt
        
    - name: Create release package
      run: |
        python create_release.py
        
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Rlooper Simulation Python v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## Rlooper Simulation Python Release v${{ steps.get_version.outputs.VERSION }}
          
          ### Features
          - Cross-platform Snakemake workflow for rlooper simulation
          - Automatic virtual environment setup
          - Support for multiple FASTA file processing
          - DAG visualization and summary reports
          
          ### Quick Start
          1. Download and extract the release package
          2. Run: `python setup.py` 
          3. Run: `python run_workflow.py all`
          
          ### Package Contents
          - Complete source code with frozen dependencies
          - Example FASTA files for testing
          - Cross-platform setup scripts
          - Comprehensive documentation
          
          See README.md for detailed installation and usage instructions.
          
        files: |
          release/rlooper_sim_python-v${{ steps.get_version.outputs.VERSION }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}